import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const RecipesPage: NextPage = () => {
  const recipes = api.recipes.getRecipes.useQuery();

  return (
    <>
      <Head>
        <title>Submit a Recipe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4 bg-gradient-to-t from-[#2e026d] to-[#15162c] text-white">
        <h1>Recipes</h1>
        <Link href="/">Home</Link>

        <h2>RECIPES</h2>
        <div>
          {recipes.data?.map((recipe) => (
            <div key={recipe.id}>
              <div>{recipe.name}</div>
              <div>{recipe.ingredient}</div>
              <div>{recipe.directions}</div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default RecipesPage;
